# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('categorySlug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300, verbose_name='E-Mail Adresi')),
                ('nameSurname', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('comments', models.TextField(verbose_name='Yorum')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
                ('commentsAllow', models.IntegerField(choices=[(0, 'Hayır'), (1, 'Evet')], default=0, verbose_name='Yorum Yayın')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('contentCount', models.IntegerField(default=0, verbose_name='Haber Okundu Sayısı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcategory', to='blog.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='postInformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='blog.Post'),
        ),
    ]
